# Broadcasting

In [5]:
import numpy as np

In [6]:
x = np.arange(3)
y = np.ones((3, 3))

x + y

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [7]:
x = np.arange(3)
y = np.arange(3)[:, np.newaxis]

In [8]:
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Regras:
1. Se os dois arrays diferem no número de dimensões, o de menor dimensão é preenchido com 1 para ficar do mesmo tamanho.
2. Se o formato dos dois arrays é diferente em alguma dimensão, o array que tem formato 1 em uma dimensão é alongado até ficar no formato do outro.
3. Se em qualquer dimensão o formato não for igual e não há um; então ocorre um erro.


### Exemplo 1

In [9]:
x = np.ones((2, 3))
y = np.arange(3)

In [10]:
x + y

array([[1., 2., 3.],
       [1., 2., 3.]])

In [11]:
print(f'Shape x: {x.shape}')
print(f'Shape y: {y.shape}')

Shape x: (2, 3)
Shape y: (3,)


In [12]:
#Regra 1
y = y[np.newaxis, :]

In [13]:
print(f'Shape x: {x.shape}')
print(f'Shape y: {y.shape}')
y

Shape x: (2, 3)
Shape y: (1, 3)


array([[0, 1, 2]])

In [14]:
#Regra 2
y = np.concatenate([y, y])
print(f'Shape x: {x.shape}')
print(f'Shape y: {y.shape}')
y

Shape x: (2, 3)
Shape y: (2, 3)


array([[0, 1, 2],
       [0, 1, 2]])

In [15]:
x + y

array([[1., 2., 3.],
       [1., 2., 3.]])

### Exemplo 2

In [16]:
x = np.ones((3, 1))
y = np.arange(3)

In [17]:
x

array([[1.],
       [1.],
       [1.]])

In [18]:
y

array([0, 1, 2])

In [19]:
x + y

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [20]:
print(f'Shape x: {x.shape}')
print(f'Shape y: {y.shape}')

Shape x: (3, 1)
Shape y: (3,)


In [21]:
#Regra 1
y = y[np.newaxis, :]

In [22]:
print(f'Shape x: {x.shape}')
print(f'Shape y: {y.shape}')
y

Shape x: (3, 1)
Shape y: (1, 3)


array([[0, 1, 2]])

In [23]:
#Regra 2
x = np.concatenate([x, x, x], axis=1)
y = np.concatenate([y, y, y])
print(f'Shape x: {x.shape}')
print(f'Shape y: {y.shape}')

Shape x: (3, 3)
Shape y: (3, 3)


In [24]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
y

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [26]:
x + y

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

## Exemplo 3

In [27]:
x = np.ones((3, 2))
y = np.arange(3)

In [28]:
x + y

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [29]:
#Regra 1
y = y[np.newaxis, :]

In [30]:
print(f'Shape x: {x.shape}')
print(f'Shape y: {y.shape}')
y

Shape x: (3, 2)
Shape y: (1, 3)


array([[0, 1, 2]])

In [31]:
#Regra 2
y = np.concatenate([y, y, y])
print(f'Shape x: {x.shape}')
print(f'Shape y: {y.shape}')

Shape x: (3, 2)
Shape y: (3, 3)


In [32]:
x

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [33]:
y

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

## Exemplo de quando usar

* Normalizar as features

In [34]:
x = np.random.random((10, 3))
x

array([[0.95817911, 0.54848078, 0.47647373],
       [0.63698809, 0.31684876, 0.09158048],
       [0.80252334, 0.99070827, 0.60153744],
       [0.31805632, 0.62419981, 0.64485868],
       [0.98581801, 0.55530886, 0.88445424],
       [0.09214195, 0.83047799, 0.37668075],
       [0.74247276, 0.57088824, 0.05203725],
       [0.13018665, 0.73850875, 0.36279618],
       [0.35585466, 0.79819361, 0.56693486],
       [0.9296398 , 0.89620766, 0.39372662]])

In [35]:
xmean = x.mean(0)
xmean

array([0.59518607, 0.68698227, 0.44510802])

In [36]:
xstd = x.std(0)
xstd

array([0.32649722, 0.19041469, 0.23807669])

In [37]:
x_normalize = (x - xmean)/xstd

In [38]:
x_normalize.mean(0)

array([-1.33226763e-16,  2.44249065e-16,  1.27675648e-16])

In [39]:
x_normalize.std(0)

array([1., 1., 1.])