# Classificador com multiplas classes
---
**Aula Prática 17**: Multiplas classes


**Objetivo**: Treinar modelos para classificação não binaria


Banco de dados:


**MNIST**
[Link](https://drive.google.com/file/d/1yQgW3xg8AKT4XmVnxHvGo5ldIzaYY0n3/view?usp=drive_link)

Dado que representa a escrita de um número. Os labels são os números de 0 a 10, cada feature representa um pixel da figura.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('mnist_train.csv')

## Treino de modelo
---


### Separação do banco entre treino e teste
O primeiro passo para se treinar um modelo é separar o banco entre treino e teste. Para isso utilizaremos a função train_test_split




``` python
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.3, random_state=15)
```
No exemplo acima X é um dataframe contendo as features do modelo e Y um dataframe com a variável target.




O parâmetro test_size controla o percentual de dados que será utilizado para teste.




O parâmetro random_state controla a aleatoriedade da geração do dado, permitindo que ao reexecutar o código seja gerado os mesmos bancos de treino e teste.




É importante separar o banco entre treino e teste, pois utilizaremos o banco de treino para treinar modelos e o banco de teste para avaliar os modelos.




### Treino do modelo
Agora que já possuímos os dados de treino e teste vamos treinar os nossos modelos


#### Regressão:
``` python
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(penalty='none')
model.fit(X_train, Y_train)
```


No código acima o objeto model é do tipo LogisticRegression, nele iremos fazer o ajuste do nosso modelo, realizar predições e também ficará armazenado nele os coeficientes do modelo.


``` python
# Para acessar os coeficientes
model.coef_
# Para acessar o intercepto
model.intercept_
# Para fazer predições de classes
model.predict(X_test)
# Para fazer predições de probabilidade
model.predict_proba(X_test)
```
--------------------------------------------
#### Random Forest:


``` python
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, Y_train)
```


No código acima o objeto model é do tipo RandomForestClassifier, nele iremos fazer o ajuste do nosso modelo, realizar predições e também ficará armazenado a árvore e a importancia das features.


``` python
# Para fazer predições de classes
model.predict(X_test)
# Para fazer predições de probabilidade
model.predict_proba(X_test)
# Para acessar a importancia
model.feature_importances_
```
----------------------------
#### XGBoost:
``` python
from xgboost import XGBClassifier
model = XGBClassifier(objective='multi:softmax')
model.fit(X_train, Y_train)
```


No código acima o objeto model é do tipo XGBClassifier, nele iremos fazer o ajuste do nosso modelo, realizar predições e também ficará armazenado a árvore e a importância das features.




``` python
# Para fazer predições de classes
model.predict(X_test)
# Para fazer predições de probabilidade
model.predict_proba(X_test)
# Para acessar a importancia
model.feature_importances_
```


### Avaliação do modelo
Para avaliar o modelo treinado utilizaremos as métricas vistas na aula teórica.




``` python
from sklearn.metrics import classification_report, confusion_matrix,


# Métricas acurácia, precisão, recall, f1-score
print(classification_report(Y_test, Y_predit))




# Matriz de confusão
confusion_matrix(Y_test, Y_predit)
```




Também é possível se obter cada uma das métricas do report
``` python
from sklearn.metrics import recall_score, precision_score, f1_score, accuracy_score




recall_score(Y_test, Y_predict, pos_label=1)
```


--------------------
### Exercício:




* Separe o banco entre treino e teste. Use 30% do banco para teste. Faça a quebra com todas as variáveis.




* Treine um modelo utilizando regressão
* Treine um modelo utilizando random forest (parâmetros default)
* Treine um modelo utilizando xgboost (parâmetros default)



#### Solução

In [10]:
import numpy as np
import pandas as pd


import warnings
warnings.filterwarnings("ignore")

In [13]:
##  importando as libs dos modelos

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

## importando as metricas

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, precision_score, f1_score, accuracy_score


In [14]:
df.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [15]:
X = df.drop("label", axis=1)
y = df[["label"]]


In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3, random_state=15)

---

In [18]:
model_1 = LogisticRegression()

In [19]:
model_1.fit(X_train, Y_train)

LogisticRegression()

In [20]:
model_1.coef_

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
model_1.intercept_

array([-6.32374549e-05,  5.22240244e-05,  4.81626437e-05, -6.68208807e-05,
        2.43496362e-05,  3.84743908e-04, -3.40927873e-05,  1.30780673e-04,
       -3.86126981e-04, -8.99827813e-05])

In [23]:
y_pred = model_1.predict(X_test)
y_pred

array([4, 2, 5, ..., 9, 1, 4], dtype=int64)

In [26]:
y_pred_prob = model_1.predict_proba(X_test)

In [27]:
y_pred_prob

array([[3.82468902e-05, 2.05918140e-09, 1.91156823e-06, ...,
        1.01179257e-06, 6.49603592e-05, 7.60446576e-05],
       [6.20762079e-05, 6.50749363e-06, 9.25134892e-01, ...,
        3.53026183e-11, 7.38411253e-02, 2.92192651e-07],
       [1.00578662e-01, 6.29096410e-08, 1.52086401e-02, ...,
        5.27578242e-07, 1.84014839e-01, 1.47016612e-03],
       ...,
       [1.18085515e-03, 1.04146878e-12, 5.45137201e-08, ...,
        4.57590817e-01, 1.56067745e-05, 5.37866635e-01],
       [6.40644702e-06, 9.80915812e-01, 3.03367672e-03, ...,
        8.74448276e-09, 1.56252070e-02, 6.84355059e-06],
       [1.51386406e-05, 1.54084826e-06, 2.51621262e-04, ...,
        2.73176062e-04, 2.87537069e-04, 2.41120761e-02]])

In [32]:
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.97      0.96      1798
           1       0.96      0.97      0.96      2024
           2       0.92      0.89      0.91      1831
           3       0.89      0.90      0.90      1820
           4       0.93      0.93      0.93      1764
           5       0.88      0.86      0.87      1591
           6       0.94      0.96      0.95      1769
           7       0.93      0.93      0.93      1845
           8       0.89      0.87      0.88      1783
           9       0.89      0.91      0.90      1775

    accuracy                           0.92     18000
   macro avg       0.92      0.92      0.92     18000
weighted avg       0.92      0.92      0.92     18000



In [34]:
print(confusion_matrix(Y_test, y_pred))

[[1739    0    5    4    3   18   12    5    9    3]
 [   0 1957   13    9    2    5    1    3   26    8]
 [   9   29 1634   40   21    7   21   17   43   10]
 [   4    5   30 1641    1   61    6   23   34   15]
 [   3    6    8    2 1641    7   18    8   16   55]
 [  20    5   27   59   14 1366   30    7   44   19]
 [  14    2   18    0   13   18 1697    1    5    1]
 [   4    4   17   13   17    2    2 1715    8   63]
 [  15   31   22   60    7   50   13    7 1557   21]
 [  12    3    3   19   51   14    1   51   11 1610]]


----

In [35]:
model_2 = RandomForestClassifier()

In [36]:
model_2.fit(X_train, Y_train)

RandomForestClassifier()

In [38]:
model_2.feature_importances_

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       5.07825715e-07, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.51486305e-06, 1.53649995e-06,
       6.44963889e-06, 1.07325627e-06, 2.48605451e-06, 9.94659160e-07,
       9.91987072e-07, 3.41682040e-06, 2.45569255e-06, 2.98674834e-06,
       4.21450551e-06, 1.88999881e-06, 9.38290094e-07, 2.64661456e-07,
       5.07200278e-07, 1.88815102e-06, 7.42331057e-07, 4.27592269e-07,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [39]:
y_pred = model_2.predict(X_test)
y_pred

array([4, 2, 5, ..., 7, 1, 4], dtype=int64)

In [40]:
y_pred_prob = model_2.predict_proba(X_test)
y_pred_prob

array([[0.02, 0.01, 0.01, ..., 0.03, 0.  , 0.05],
       [0.  , 0.  , 0.84, ..., 0.02, 0.06, 0.01],
       [0.03, 0.  , 0.06, ..., 0.03, 0.05, 0.13],
       ...,
       [0.  , 0.  , 0.  , ..., 0.86, 0.  , 0.08],
       [0.  , 0.96, 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.06, 0.02, 0.04]])

In [41]:
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      1798
           1       0.99      0.98      0.99      2024
           2       0.96      0.97      0.96      1831
           3       0.96      0.95      0.96      1820
           4       0.97      0.98      0.97      1764
           5       0.96      0.96      0.96      1591
           6       0.98      0.98      0.98      1769
           7       0.98      0.96      0.97      1845
           8       0.96      0.96      0.96      1783
           9       0.96      0.95      0.96      1775

    accuracy                           0.97     18000
   macro avg       0.97      0.97      0.97     18000
weighted avg       0.97      0.97      0.97     18000



In [42]:
print(confusion_matrix(Y_test, y_pred))

[[1779    0    3    1    1    1    4    0    9    0]
 [   0 1992   10    4    2    2    3    2    5    4]
 [   7    6 1771    7   12    1   10    8    7    2]
 [   2    2   18 1732    0   19    2   15   19   11]
 [   2    2    3    0 1725    0    5    1    6   20]
 [   8    1    4   19    3 1530    9    0   11    6]
 [   7    2    1    0    2   13 1739    0    5    0]
 [   2    6   20    2   11    1    0 1779    5   19]
 [   7    7   10   14    7   17    3    3 1705   10]
 [  12    2    4   19   21    6    1   12   10 1688]]


----

In [43]:
model_3 = XGBClassifier()

In [44]:
model_3.fit(X_train, Y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob', ...)

In [46]:
model_3.feature_importances_

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [48]:
y_pred = model_3.predict(X_test)
y_pred

array([4, 2, 5, ..., 7, 1, 4], dtype=int64)

In [49]:
y_pred_prob = model_3.predict_proba(X_test)
y_pred_prob

array([[2.61987429e-06, 4.23706842e-06, 1.75320729e-05, ...,
        4.56399212e-05, 6.75433193e-06, 2.16388180e-05],
       [6.67066161e-07, 9.19806735e-06, 9.99889731e-01, ...,
        8.76169850e-07, 3.77640754e-05, 1.74281092e-06],
       [1.08879185e-05, 2.41553380e-06, 8.65560742e-06, ...,
        4.17430101e-06, 1.53532339e-04, 2.79800533e-05],
       ...,
       [4.58406721e-05, 1.01237777e-06, 2.07398216e-06, ...,
        9.98443425e-01, 7.61011165e-07, 1.35528820e-03],
       [4.33027452e-07, 9.99931455e-01, 1.00817997e-05, ...,
        9.47008903e-06, 3.11724034e-05, 9.10512881e-07],
       [6.84153747e-07, 1.04627475e-06, 7.52093820e-06, ...,
        7.56356021e-05, 6.83830513e-06, 3.22832668e-04]], dtype=float32)

In [50]:
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1798
           1       0.99      0.98      0.99      2024
           2       0.97      0.97      0.97      1831
           3       0.98      0.96      0.97      1820
           4       0.97      0.98      0.97      1764
           5       0.97      0.97      0.97      1591
           6       0.98      0.98      0.98      1769
           7       0.98      0.98      0.98      1845
           8       0.97      0.97      0.97      1783
           9       0.96      0.97      0.96      1775

    accuracy                           0.98     18000
   macro avg       0.98      0.98      0.98     18000
weighted avg       0.98      0.98      0.98     18000



In [51]:
print(confusion_matrix(Y_test, y_pred))

[[1775    0    2    3    2    1    5    1    8    1]
 [   0 1992   10    5    1    3    1    3    6    3]
 [   2    6 1782   12    7    0    4   13    4    1]
 [   1    1   13 1756    3   13    1    7   14   11]
 [   0    2    3    0 1731    0    2    0    5   21]
 [   7    2    2    7    3 1547   12    0    5    6]
 [   5    2    0    1    3   11 1740    0    6    1]
 [   2    1   10    1    7    0    0 1806    4   14]
 [   7    5    5    8    7    7    5    3 1731    5]
 [   6    2    1    5   26    9    0    9    4 1713]]
